In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
pd.set_option('max_columns', 50)
%matplotlib inline

In [2]:
x = np.r_[1, 2, 3]
y = np.r_[4, 6, 8]
x @ y.T 


40

In [3]:
msa = (y - x).mean(axis=None)

In [4]:
msa

4.0

In [40]:
z = np.r_[3, 5, 7, 9]
index = [0, 1]
new_z = np.delete(z, index)
np.append(new_z, np.repeat(np.nan, 2))

array([  7.,   9.,  nan,  nan])

In [41]:
index2 = [2, 3]
new_z2 = np.delete(z, index2)
print (np.r_[np.repeat(np.nan, 2),new_z2])

[ nan  nan   3.   5.]


In [42]:
np.random.seed(55555)
n=4
d=2 
A=np.random.rand(n,d)
B=np.random.rand(n,1) 

In [43]:
A

array([[ 0.12910447,  0.87215227],
       [ 0.79550388,  0.87877053],
       [ 0.44954347,  0.57533973],
       [ 0.82941516,  0.87311489]])

In [44]:
B

array([[ 0.14097073],
       [ 0.8995075 ],
       [ 0.88931461],
       [ 0.75743052]])

In [45]:
(A-B)**2

array([[  1.40808311e-04,   5.34626434e-01],
       [  1.08167515e-02,   4.30021954e-04],
       [  1.93398651e-01,   9.85802255e-02],
       [  5.18178777e-03,   1.33828727e-02]])

In [46]:
%cd /Users/matteoballerinipuviani/UU/QUEA/we

/Users/matteoballerinipuviani/UU/QUEA/we


In [47]:
flights = pd.read_csv("flights.csv")

In [48]:
flights.head()

origin  year  month  day  hour   temp   dewp  humid  wind_dir  wind_speed  \
0    EWR  2013      1    1     0  37.04  21.92  53.97     230.0    10.35702   
1    EWR  2013      1    1     1  37.04  21.92  53.97     230.0    13.80936   
2    EWR  2013      1    1     2  37.94  21.92  52.09     230.0    12.65858   
3    EWR  2013      1    1     3  37.94  23.00  54.51     230.0    13.80936   
4    EWR  2013      1    1     4  37.94  24.08  57.04     240.0    14.96014   

   wind_gust  precip  pressure  visib            time_hour  
0  11.918651     0.0    1013.9   10.0  2013-01-01 01:00:00  
1  15.891535     0.0    1013.0   10.0  2013-01-01 02:00:00  
2  14.567241     0.0    1012.6   10.0  2013-01-01 03:00:00  
3  15.891535     0.0    1012.7   10.0  2013-01-01 04:00:00  
4  17.215830     0.0    1012.8   10.0  2013-01-01 05:00:00

In [24]:
flights["celsius"] = (flights.temp - 32) * 5/9


In [25]:
flights.head()

origin  year  month  day  hour   temp   dewp  humid  wind_dir  wind_speed  \
0    EWR  2013      1    1     0  37.04  21.92  53.97     230.0    10.35702   
1    EWR  2013      1    1     1  37.04  21.92  53.97     230.0    13.80936   
2    EWR  2013      1    1     2  37.94  21.92  52.09     230.0    12.65858   
3    EWR  2013      1    1     3  37.94  23.00  54.51     230.0    13.80936   
4    EWR  2013      1    1     4  37.94  24.08  57.04     240.0    14.96014   

   wind_gust  precip  pressure  visib            time_hour  celsius  
0  11.918651     0.0    1013.9   10.0  2013-01-01 01:00:00      2.8  
1  15.891535     0.0    1013.0   10.0  2013-01-01 02:00:00      2.8  
2  14.567241     0.0    1012.6   10.0  2013-01-01 03:00:00      3.3  
3  15.891535     0.0    1012.7   10.0  2013-01-01 04:00:00      3.3  
4  17.215830     0.0    1012.8   10.0  2013-01-01 05:00:00      3.3

In [26]:
jfk = flights.loc[flights['origin'] == 'JFK']

In [27]:
jfk

origin  year  month  day  hour   temp   dewp  humid  wind_dir  \
8708     JFK  2013      1    1     0  37.94  23.00  54.51     240.0   
8709     JFK  2013      1    1     1  37.94  24.08  57.04     250.0   
8710     JFK  2013      1    1     2  39.02  24.98  56.77     240.0   
8711     JFK  2013      1    1     3  39.02  26.06  59.37     240.0   
8712     JFK  2013      1    1     4  39.02  24.98  56.77     260.0   
8713     JFK  2013      1    1     6  39.02  26.06  59.37     260.0   
8714     JFK  2013      1    1     7  39.02  26.06  59.37     270.0   
8715     JFK  2013      1    1     8  39.92  26.96  59.50     260.0   
8716     JFK  2013      1    1     9  39.92  28.04  62.21     250.0   
8717     JFK  2013      1    1    10  39.02  26.96  61.63     260.0   
8718     JFK  2013      1    1    11  37.94  26.96  64.29     260.0   
8719     JFK  2013      1    1    12  39.02  28.04  64.43     260.0   
8720     JFK  2013      1    1    13  39.92  26.96  59.50     260.0   
8721     JFK  2013      1    1    14  39.92  26.96  59.50     260.0   
8722     JFK  2013      1    1    15  41.00  28.04  59.65     260.0   
8723     JFK  2013      1    1    16  41.00  26.96  57.06     270.0   
8724     JFK  2013      1    1    17  39.92  26.06  57.33     290.0   
8725     JFK  2013      1    1    18  37.40  26.60  64.70     340.0   
8726     JFK  2013      1    1    19  39.02  24.08  54.68     310.0   
8727     JFK  2013      1    1    20  39.02  23.00  52.26     290.0   
8728     JFK  2013      1    1    21  37.94  17.96  44.00     320.0   
8729     JFK  2013      1    1    22  37.04  17.06  43.85     330.0   
8730     JFK  2013      1    1    23  35.06  14.00  41.51     310.0   
8731     JFK  2013      1    2     0  33.08  14.00  44.92     350.0   
8732     JFK  2013      1    2     1  32.00  14.00  46.92     330.0   
8733     JFK  2013      1    2     2  30.02  10.94  44.41     330.0   
8734     JFK  2013      1    2     3  28.94  10.94  46.41     320.0   
8735     JFK  2013      1    2     4  26.96   8.06  44.25     320.0   
8736     JFK  2013      1    2     5  26.06   8.06  45.93     320.0   
8737     JFK  2013      1    2     6  26.06   8.06  45.93     330.0   
...      ...   ...    ...  ...   ...    ...    ...    ...       ...   
15747    JFK  2013     10   21    18  64.94  35.96  34.06     180.0   
15748    JFK  2013     10   21    19  64.04  41.00  42.82     170.0   
15749    JFK  2013     10   21    20  62.96  39.92  42.65     180.0   
15750    JFK  2013     10   21    21  60.98  39.92  45.74     180.0   
15751    JFK  2013     10   21    22  60.08  42.98  53.15     190.0   
15752    JFK  2013     10   21    23  60.08  46.04  59.72     190.0   
15753    JFK  2013     10   22     0  59.00  48.92  69.17     200.0   
15754    JFK  2013     10   22     1  59.00  46.94  64.22     200.0   
15755    JFK  2013     10   22     2  59.00  46.94  64.22     210.0   
15756    JFK  2013     10   22     3  59.00  48.02  66.88     200.0   
15757    JFK  2013     10   22     4  59.00  48.02  66.88     210.0   
15758    JFK  2013     10   22     5  57.92  48.02  69.52     210.0   
15759    JFK  2013     10   22     6  55.94  48.02  74.67     220.0   
15760    JFK  2013     10   22     7  55.04  48.02  77.15     220.0   
15761    JFK  2013     10   22     8  55.94  50.00  80.40     220.0   
15762    JFK  2013     10   22     9  53.96  48.92  83.00     230.0   
15763    JFK  2013     10   22    10  55.94  48.92  77.23     230.0   
15764    JFK  2013     10   22    11  57.02  48.92  74.27     220.0   
15765    JFK  2013     10   22    12  60.98  50.00  67.11     200.0   
15766    JFK  2013     10   22    13  62.96  48.92  60.11     210.0   
15767    JFK  2013     10   22    14  64.04  46.94  53.73     220.0   
15768    JFK  2013     10   22    15  66.92  46.04  46.98     230.0   
15769    JFK  2013     10   22    16  66.02  46.94  50.14     230.0   
15770    JFK  2013     10   22    17  68.00  46.04  45.26     230.0   
15771    JFK  2013     10   22

In [28]:
jfk_grouped = jfk.groupby(['month', "day"]).mean()
print(jfk_grouped)

             year       hour       temp       dewp      humid    wind_dir  \
month day                                                                   
1     1    2013.0  11.782609  38.871304  24.776522  56.926087  273.478261   
      2    2013.0  11.500000  28.542500   9.837500  45.210417  320.000000   
      3    2013.0  11.500000  29.772500  13.970000  51.621667  298.333333   
      4    2013.0  11.500000  34.032500  19.452500  55.007917  256.250000   
      5    2013.0  11.500000  36.897500  19.197500  48.918750  279.166667   
      6    2013.0  11.500000  37.452500  28.302500  70.232500  237.500000   
      7    2013.0  11.500000  41.862500  24.245000  50.292083  282.083333   
      8    2013.0  11.500000  38.675000  28.227500  66.891667  195.000000   
      9    2013.0  11.500000  40.835000  33.905000  76.847500  170.000000   
      10   2013.0  11.500000  45.050000  25.647500  47.599167  293.333333   
      11   2013.0  11.500000  40.115000  29.217500  65.903333   86.250000   

In [37]:
jfk_grouped['match'] = jfk_grouped.celsius.gt(jfk_grouped.celsius.shift())
jfk_grouped.head(10)

year       hour       temp       dewp      humid    wind_dir  \
month day                                                                   
1     1    2013.0  11.782609  38.871304  24.776522  56.926087  273.478261   
      2    2013.0  11.500000  28.542500   9.837500  45.210417  320.000000   
      3    2013.0  11.500000  29.772500  13.970000  51.621667  298.333333   
      4    2013.0  11.500000  34.032500  19.452500  55.007917  256.250000   
      5    2013.0  11.500000  36.897500  19.197500  48.918750  279.166667   
      6    2013.0  11.500000  37.452500  28.302500  70.232500  237.500000   
      7    2013.0  11.500000  41.862500  24.245000  50.292083  282.083333   
      8    2013.0  11.500000  38.675000  28.227500  66.891667  195.000000   
      9    2013.0  11.500000  40.835000  33.905000  76.847500  170.000000   
      10   2013.0  11.500000  45.050000  25.647500  47.599167  293.333333   

           wind_speed  wind_gust  precip     pressure    visib   celsius  \
month day                                                                  
1     1     15.410445  17.734032     0.0  1012.663636  10.0000  3.817391   
      2     15.679378  18.043514     0.0  1017.287500  10.0000 -1.920833   
      3     11.316003  13.022230     0.0  1021.225000  10.0000 -1.237500   
      4     15.775276  18.153872     0.0  1017.854167  10.0000  1.129167   
      5     13.665512  15.725998     0.0  1021.262500  10.0000  2.720833   
      6      9.877528  11.366862     0.0  1020.305556   8.9375  3.029167   
      7     10.357020  11.918651     0.0  1023.083333  10.0000  5.479167   
      8      9.206240  10.594357     0.0  1029.316667  10.0000  3.708333   
      9      6.041595   6.952547     0.0  1027.041667   9.5000  4.908333   
      10    14.049106  16.167430     0.0  1028.937500  10.0000  7.250000   

           match  
month day         
1     1    False  
      2    False  
      3     True  
      4     True  
      5     True  
      6     True  
      7     True  
      8    False  
      9     True  
      10    True

In [29]:
jfk_grouped.sort_values('celsius', ascending=False).head(5)

year  hour     temp     dewp      humid    wind_dir  wind_speed  \
month day                                                                      
7     17   2013.0  11.5  87.0425  66.2900  50.984167  222.500000    7.144426   
      16   2013.0  11.5  86.8700  65.9675  52.828333  238.333333    9.541884   
      20   2013.0  11.5  86.4425  71.9450  63.582500  236.956522   14.910106   
      18   2013.0  11.5  86.4350  71.7050  63.893333  236.086957    9.637782   
      19   2013.0  11.5  86.3375  75.9725  72.028750  192.916667   10.452918   

           wind_gust  precip     pressure      visib    celsius  
month day                                                        
7     17    8.221662     0.0  1020.970833  10.000000  30.579167  
      16   10.980609     0.0  1021.312500  10.000000  30.483333  
      20   17.158252     0.0  1008.926087   8.750000  30.245833  
      18   11.090967     0.0  1017.020833   9.666667  30.241667  
      19   12.029009     0.0  1013.420833   8.375000  30.187500

In [22]:
flights.head()

origin  year  month  day  hour   temp   dewp  humid  wind_dir  wind_speed  \
0    EWR  2013      1    1     0  37.04  21.92  53.97     230.0    10.35702   
1    EWR  2013      1    1     1  37.04  21.92  53.97     230.0    13.80936   
2    EWR  2013      1    1     2  37.94  21.92  52.09     230.0    12.65858   
3    EWR  2013      1    1     3  37.94  23.00  54.51     230.0    13.80936   
4    EWR  2013      1    1     4  37.94  24.08  57.04     240.0    14.96014   

   wind_gust  precip  pressure  visib            time_hour  celsius  
0  11.918651     0.0    1013.9   10.0  2013-01-01 01:00:00      2.8  
1  15.891535     0.0    1013.0   10.0  2013-01-01 02:00:00      2.8  
2  14.567241     0.0    1012.6   10.0  2013-01-01 03:00:00      3.3  
3  15.891535     0.0    1012.7   10.0  2013-01-01 04:00:00      3.3  
4  17.215830     0.0    1012.8   10.0  2013-01-01 05:00:00      3.3

In [23]:
display(flights[["year", "month", "day"]].head())

year  month  day
0  2013      1    1
1  2013      1    1
2  2013      1    1
3  2013      1    1
4  2013      1    1

In [25]:
display(flights[["hour", "temp", "dewp", "humid", "wind_dir", "wind_speed", "wind_gust", "precip", "pressure", "visib", "time_hour", "celsius", "origin"]].head())

hour   temp   dewp  humid  wind_dir  wind_speed  wind_gust  precip  \
0     0  37.04  21.92  53.97     230.0    10.35702  11.918651     0.0   
1     1  37.04  21.92  53.97     230.0    13.80936  15.891535     0.0   
2     2  37.94  21.92  52.09     230.0    12.65858  14.567241     0.0   
3     3  37.94  23.00  54.51     230.0    13.80936  15.891535     0.0   
4     4  37.94  24.08  57.04     240.0    14.96014  17.215830     0.0   

   pressure  visib            time_hour  celsius origin  
0    1013.9   10.0  2013-01-01 01:00:00      2.8    EWR  
1    1013.0   10.0  2013-01-01 02:00:00      2.8    EWR  
2    1012.6   10.0  2013-01-01 03:00:00      3.3    EWR  
3    1012.7   10.0  2013-01-01 04:00:00      3.3    EWR  
4    1012.8   10.0  2013-01-01 05:00:00      3.3    EWR

In [26]:
url1 = "https://raw.githubusercontent.com/DavidePosillipo/ProbabilityAndStatistics/master/Assignment_1/data/some_birth_dates1.csv"

In [27]:
url2 = "https://raw.githubusercontent.com/DavidePosillipo/ProbabilityAndStatistics/master/Assignment_1/data/some_birth_dates2.csv"

In [28]:
url3 = "https://raw.githubusercontent.com/DavidePosillipo/ProbabilityAndStatistics/master/Assignment_1/data/some_birth_dates3.csv"

In [40]:
A = pd.read_table(url1, sep=',')
A.head()
B = pd.read_table(url2, sep=',')
B.head()
C = pd.read_table(url3, sep=',')
C.head()

Name   BirthDate
0         Jodoc Alwin  16.11.1969
1  Hushang Naigamwala  25.08.1991
2            Zhen Wei  16.11.1975
3       Noe Tae-Woong  11.07.1970
4    Didier Cuvillier  24.04.1938

In [44]:
D = pd.merge(A, B, on='Name', how='outer')
print(D)


                   Name BirthDate_x BirthDate_y
0      Paitoon Ornwimol  26.06.1958         NaN
1          Antónia Lata  20.05.1935         NaN
2     Bertoldo Mallozzi  17.08.1972         NaN
3         Nedeljko Bukv  19.12.1921         NaN
4         Micha Kitchen  17.09.1930  17.09.1930
5       Mefodiy Shachar  01.10.1914  01.10.1914
6          Paul Meckler  29.09.1968  29.09.1968
7       Katarzyna Lasko  20.10.1971  20.10.1971
8          Åge Trelstad  07.03.1935  07.03.1935
9   Duchanee Panomyaong  19.06.1952  19.06.1952
10   Hushang Naigamwala         NaN  25.08.1991
11             Zhen Wei         NaN  16.11.1975
12          Jodoc Alwin         NaN  16.11.1969
13           Igor Mazał         NaN  14.05.2004
14        Noe Tae-Woong         NaN  11.07.1970


In [46]:
E = pd.merge(D, C, on="Name", how="outer")
print(E)

                   Name BirthDate_x BirthDate_y   BirthDate
0      Paitoon Ornwimol  26.06.1958         NaN         NaN
1          Antónia Lata  20.05.1935         NaN         NaN
2     Bertoldo Mallozzi  17.08.1972         NaN         NaN
3         Nedeljko Bukv  19.12.1921         NaN         NaN
4         Micha Kitchen  17.09.1930  17.09.1930         NaN
5       Mefodiy Shachar  01.10.1914  01.10.1914         NaN
6          Paul Meckler  29.09.1968  29.09.1968         NaN
7       Katarzyna Lasko  20.10.1971  20.10.1971         NaN
8          Åge Trelstad  07.03.1935  07.03.1935         NaN
9   Duchanee Panomyaong  19.06.1952  19.06.1952         NaN
10   Hushang Naigamwala         NaN  25.08.1991  25.08.1991
11             Zhen Wei         NaN  16.11.1975  16.11.1975
12          Jodoc Alwin         NaN  16.11.1969  16.11.1969
13           Igor Mazał         NaN  14.05.2004         NaN
14        Noe Tae-Woong         NaN  11.07.1970  11.07.1970
15     Didier Cuvillier         NaN     

In [47]:
F = pd.merge(A, B, on='Name', how='inner')
print(F)

                  Name BirthDate_x BirthDate_y
0        Micha Kitchen  17.09.1930  17.09.1930
1      Mefodiy Shachar  01.10.1914  01.10.1914
2         Paul Meckler  29.09.1968  29.09.1968
3      Katarzyna Lasko  20.10.1971  20.10.1971
4         Åge Trelstad  07.03.1935  07.03.1935
5  Duchanee Panomyaong  19.06.1952  19.06.1952


In [48]:
G = pd.merge(A, C, on='Name', how='inner')
print(G)

Empty DataFrame
Columns: [Name, BirthDate_x, BirthDate_y]
Index: []


In [49]:
H = pd.merge(A, B, on='Name', how='left')
print(H)

                  Name BirthDate_x BirthDate_y
0     Paitoon Ornwimol  26.06.1958         NaN
1         Antónia Lata  20.05.1935         NaN
2    Bertoldo Mallozzi  17.08.1972         NaN
3        Nedeljko Bukv  19.12.1921         NaN
4        Micha Kitchen  17.09.1930  17.09.1930
5      Mefodiy Shachar  01.10.1914  01.10.1914
6         Paul Meckler  29.09.1968  29.09.1968
7      Katarzyna Lasko  20.10.1971  20.10.1971
8         Åge Trelstad  07.03.1935  07.03.1935
9  Duchanee Panomyaong  19.06.1952  19.06.1952
